name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.0.0
        with:
          python-version: '3.11'

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@4d4cb0ab842247caea1963132c242c62aab1e4d5 # v10.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "--no-push"

      - name: Create release PR
        id: create-pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7.0.8
        if: steps.release.outputs.released == 'true'
        with:
          commit-message: "chore(release): prepare version bump"
          title: "chore(release): prepare version bump"
          branch: release-bot/version-bump-${{ github.run_id }}
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true

      - name: Output if no PR created
        if: steps.release.outputs.released == 'true' && steps.create-pr.outputs.pull-request-number == ''
        run: echo "No release PR was created."
      - name: Check if auto-merge is enabled
        id: check-auto-merge
        run: |
          AUTO_MERGE_ENABLED=$(curl -s -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }} \
            | jq -r '.allow_auto_merge')
          echo "Auto-merge enabled: $AUTO_MERGE_ENABLED"
          echo "auto_merge_enabled=$AUTO_MERGE_ENABLED" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.release.outputs.released == 'true' && steps.create-pr.outputs.pull-request-number != '' && steps.check-auto-merge.outputs.auto_merge_enabled == 'true'
        run: gh pr merge --auto --squash ${{ steps.create-pr.outputs.pull-request-number }} || echo "Auto-merge failed. Please check repository settings and branch protection rules."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output if auto-merge not enabled
        if: steps.release.outputs.released == 'true' && steps.create-pr.outputs.pull-request-number != '' && steps.check-auto-merge.outputs.auto_merge_enabled != 'true'
        run: echo "Auto-merge is not enabled for this repository. Please merge the release PR manually at https://github.com/${{ github.repository }}/pull/${{ steps.create-pr.outputs.pull-request-number }}"
      - name: Publish to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@0a92b5d7ebfc15a84f9801ebd1bf706343d43711 # v9.8.9
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}

  build:
    name: Build binaries on ${{ matrix.os }} - ${{ matrix.arch }}
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos
            arch: arm64
            runner: macos-14
            artifact_name: maniforge-macos-arm64
          - os: macos
            arch: x86_64
            runner: macos-13
            artifact_name: maniforge-macos-x86_64
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            artifact_name: maniforge-linux-x86_64
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            artifact_name: maniforge-linux-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v6.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyyaml

      - name: Build executable
        run: |
          pyinstaller --clean maniforge.spec

      - name: Rename executable
        run: |
          mv dist/maniforge dist/${{ matrix.artifact_name }}

      - name: Make executable
        run: |
          chmod +x dist/${{ matrix.artifact_name }}

      - name: Test executable
        run: |
          dist/${{ matrix.artifact_name }} --help

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

  upload:
    name: Upload binaries to release
    needs: [release, build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: dist

      - name: Display structure
        run: ls -R dist

      - name: Calculate SHA256 checksums
        run: |
          cd dist
          for dir in */; do
            cd "$dir"
            for file in maniforge-*; do
              sha256sum "$file" >> ../SHA256SUMS
            done
            cd ..
          done
          cat SHA256SUMS

      - name: Upload binaries to release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: |
            dist/maniforge-macos-arm64/maniforge-macos-arm64
            dist/maniforge-macos-x86_64/maniforge-macos-x86_64
            dist/maniforge-linux-x86_64/maniforge-linux-x86_64
            dist/maniforge-linux-arm64/maniforge-linux-arm64
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
