name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@main
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}

  build:
    name: Build binaries on ${{ matrix.os }} - ${{ matrix.arch }}
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos
            arch: arm64
            runner: macos-14
            artifact_name: maniforge-macos-arm64
          - os: macos
            arch: x86_64
            runner: macos-13
            artifact_name: maniforge-macos-x86_64
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
            artifact_name: maniforge-linux-x86_64
          - os: linux
            arch: arm64
            runner: ubuntu-latest
            artifact_name: maniforge-linux-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.tag }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyyaml

      - name: Build executable
        run: |
          pyinstaller --clean maniforge.spec

      - name: Rename executable
        run: |
          mv dist/maniforge dist/${{ matrix.artifact_name }}

      - name: Make executable
        run: |
          chmod +x dist/${{ matrix.artifact_name }}

      - name: Test executable
        run: |
          dist/${{ matrix.artifact_name }} --help

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

  upload:
    name: Upload binaries to release
    needs: [release, build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display structure
        run: ls -R dist

      - name: Calculate SHA256 checksums
        run: |
          cd dist
          for dir in */; do
            cd "$dir"
            for file in maniforge-*; do
              sha256sum "$file" >> ../SHA256SUMS
            done
            cd ..
          done
          cat SHA256SUMS

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: |
            dist/maniforge-macos-arm64/maniforge-macos-arm64
            dist/maniforge-macos-x86_64/maniforge-macos-x86_64
            dist/maniforge-linux-x86_64/maniforge-linux-x86_64
            dist/maniforge-linux-arm64/maniforge-linux-arm64
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
